name: middle
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  firebase_core: ^2.19.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.4.0
  flutter_chat_ui: ^1.6.12
  flutter_animate: ^4.1.1+1
  flutter_cache_manager: ^3.3.0
  flutter_credit_card: ^3.0.6
  flutter_datetime_picker: ^1.5.1
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.1.0
  from_css_color: ^2.0.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  image_picker: ^0.8.6
  json_path: ^0.4.1
  mime_type: ^1.0.0
  page_transition: ^2.0.4
  path_provider: ^2.0.15
  photo_view: ^0.14.0
  provider: ^6.0.4
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1
  sign_in_with_apple: ^4.3.0
  smooth_page_indicator: ^1.0.1
  sqflite: ^2.2.6
  stream_transform: ^2.1.0
  text_search: ^0.0.2
  timeago: ^3.2.2
  url_launcher: ^6.1.10
  video_player: ^2.6.0
  cupertino_icons: ^1.0.0
  file_picker: ^8.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/